stages:
  - build
  - test
  - review
  - doc
  - deploy

variables:
  TEST_IMAGE: ${CI_REGISTRY_IMAGE}/test_2_3:$CI_COMMIT_REF_SLUG
  TEST_LATEST: ${CI_REGISTRY_IMAGE}/test_2_3:latest
  TEST_IMAGE_2_6: ${CI_REGISTRY_IMAGE}/test_2_6:$CI_COMMIT_REF_SLUG
  TEST_LATEST_2_6: ${CI_REGISTRY_IMAGE}/test_2_6:latest
  REVIEW_HOST: ${CI_BUILD_REF_SLUG}.ci.ekylibre.dev
  KUBE_NAMESPACE: eky-test-deploy

#  PROD_RAILS: ${CI_REGISTRY_IMAGE}/ekylibre-rails:$CI_COMMIT_REF_SLUG
#  PROD_RAILS_LATEST: ${CI_REGISTRY_IMAGE}/ekylibre-rails:latest
#  PROD_WEB: ${CI_REGISTRY_IMAGE}/ekylibre-web:$CI_COMMIT_REF_SLUG
#  PROD_WEB_LATEST: ${CI_REGISTRY_IMAGE}/ekylibre-web:latest


#########################################
#                 BUILD                 #
#########################################
build_test_2_3:
  image: registry.gitlab.com/ekylibre/docker-base-images/tools/deploy:1
  stage: build
  interruptible: true
  except:
    - tags
  services:
    - docker:18-dind
  before_script:
    - echo "${CI_BUILD_TOKEN}" | docker login --username $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
  script:
    - /exec ruby /build.rb -v -r $CI_COMMIT_REF_SLUG -b $CI_REGISTRY_IMAGE -f docker/test/Dockerfile -i test_2_3

build_test_2_6:
  image: registry.gitlab.com/ekylibre/docker-base-images/tools/deploy:1
  stage: build
  except:
    - tags
  services:
    - docker:18-dind
  before_script:
    - echo "${CI_BUILD_TOKEN}" | docker login --username $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
  script:
    - /exec ruby /build.rb -v -r $CI_COMMIT_REF_SLUG -b $CI_REGISTRY_IMAGE -f docker/test/Dockerfile_2_6 -i test_2_6

build_ci:
  image: registry.gitlab.com/ekylibre/docker-base-images/tools/deploy:1
  stage: build
  when: manual
  only:
    - branches
  variables:
    RUBY_VERSION: "2.3"
  services:
    - docker:18-dind
  before_script:
    - apk add openssh-client
    - /install-ssh-key $PLUGIN_SSH_KEY
    - echo "${CI_BUILD_TOKEN}" | docker login --username $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
  script:
    - for plugin in $EKYLIBRE_PLUGINS; do echo "git@gitlab.com:ekylibre/ekylibre-${plugin}.git" && git clone "git@gitlab.com:ekylibre/ekylibre-${plugin}.git" "plugins/${plugin}"; done
    - /exec ruby /build.rb -v -r $CI_COMMIT_REF_SLUG -b $CI_REGISTRY_IMAGE -f docker/prod/Dockerfile -i ci-rails-aio-2.3


.review_key: &REVIEW_KEY
  name: review/eky/$CI_BUILD_REF_NAME

.review_branches: &REVIEW_BRANCHES
  only:
    - branches
  except:
    - prod
    - core

.default_review: &DEFAULT_REVIEW
  <<: *REVIEW_BRANCHES
  environment:
    <<: *REVIEW_KEY
    url: https://$REVIEW_HOST
    on_stop: review_stop

review_start:
  <<: *DEFAULT_REVIEW
  stage: review
  dependencies:
    - build_ci
  image: registry.gitlab.com/ekylibre/helm-charts/ci-tool:master
  variables:
    GIT_STRATEGY: none
  script:
    - (cd /apps/eky-ci && helm dep update)
    - helm tiller run "$KUBE_NAMESPACE" -- helm upgrade
      --install
      --namespace "$KUBE_NAMESPACE"
      --set eky.image.tag=$CI_COMMIT_REF_SLUG
      --set eky.postgres.database=$CI_COMMIT_REF_SLUG
      --set eky.ingress.domain=${REVIEW_HOST}
      --set eky.rails.init.tenants[0]=demo1
      --set eky.rails.load.tenants[0]=demo
      --set eky.rails.load.lexicon=true
      ci-eky-${CI_COMMIT_REF_SLUG} /apps/eky-ci
  when: manual

review_stop:
  <<: *REVIEW_BRANCHES
  environment:
    <<: *REVIEW_KEY
    action: stop
  stage: review
  image: registry.gitlab.com/ekylibre/docker-base-images/tools/deploy:1
  variables:
    GIT_STRATEGY: none
  script:
    - helm tiller run "$KUBE_NAMESPACE" -- helm delete --purge ci-eky-${CI_COMMIT_REF_SLUG}
  when: manual

doc_build:
  image: registry.gitlab.com/ekylibre/docker-base-images/tools/deploy:1
  stage: doc
  only:
    - tags
  dependencies:
    - build_test_2_3
  services:
    - docker:18-dind
  before_script:
    - echo "${CI_BUILD_TOKEN}" | docker login --username $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
  script:
    - /exec ruby /build.rb -v -a TEST_IMAGE -r $CI_COMMIT_REF_SLUG -b $CI_REGISTRY_IMAGE -f docker/doc/Dockerfile -i doc

deploy_doc:
  image: registry.gitlab.com/ekylibre/helm-charts/ci-tool:master
  stage: deploy
  dependencies:
    - doc_build
  only:
    - tags
  when: manual
  variables:
    GIT_STRATEGY: none
    KUBE_DOC_NAMESPACE: ekylibre-doc
  script:
    - helm --kube-context ekylibre-doc tiller run "$KUBE_DOC_NAMESPACE" --
      helm upgrade
      --install
      --namespace "$KUBE_DOC_NAMESPACE"
      --set doc.component=ekylibre
      --set doc.version=latest
      --set image.repository=registry.gitlab.com/ekylibre/eky/doc
      --set image.tag=${CI_COMMIT_REF_SLUG}
      ekylibre-latest
      /apps/doc

#########################################
#               TEMPLATES               #
#########################################
.test_tpl: &test_task
  stage: test
  variables: &test_task_variables
    # POSTGRES VARIABLES
    POSTGRES_HOST: 127.0.0.1
    REDIS_URL: redis://127.0.0.1:6379/
    POSTGRES_USER: ekylibre
    POSTGRES_DB: ekylibre_test
    TZ: Europe/Paris
    GIT_STRATEGY: none
  services:
    - mdillon/postgis:9.6-alpine
    - redis:5.0-alpine
  except:
    - tags
  tags:
    - kubernetes
  script:
    - env
    - bash /app/test/ci/run_tests ${TASK}

.test_tpl_2_3: &test_task_2_3
  <<: *test_task
  image: $TEST_IMAGE
  dependencies:
    - build_test_2_3

.test_tpl_2_6: &test_task_2_6
  <<: *test_task
  image: $TEST_IMAGE_2_6
  dependencies:
    - build_test_2_6


#########################################
#                 TESTS                 #
#########################################
test_concepts:
  <<: *test_task_2_3
  variables:
    <<: *test_task_variables
    TASK: test:concepts
test_controllers:
  <<: *test_task_2_3
  variables:
    <<: *test_task_variables
    TASK: test:controllers
test_exchangers:
  <<: *test_task_2_3
  variables:
    <<: *test_task_variables
    TASK: test:exchangers
test_helpers:
  <<: *test_task_2_3
  variables:
    <<: *test_task_variables
    TASK: test:helpers
test_jobs:
  <<: *test_task_2_3
  variables:
    <<: *test_task_variables
    TASK: test:jobs
test_lib:
  <<: *test_task_2_3
  variables:
    <<: *test_task_variables
    TASK: test:lib
test_models:
  <<: *test_task_2_3
  variables:
    <<: *test_task_variables
    TASK: test:models
test_services:
  <<: *test_task_2_3
  variables:
    <<: *test_task_variables
    TASK: test:services
test_validators:
  <<: *test_task_2_3
  variables:
    <<: *test_task_variables
    TASK: test:validators


test_concepts_2_6:
  <<: *test_task_2_6
  variables:
    <<: *test_task_variables
    TASK: test:concepts
test_controllers_2_6:
  <<: *test_task_2_6
  variables:
    <<: *test_task_variables
    TASK: test:controllers
test_exchangers_2_6:
  <<: *test_task_2_6
  variables:
    <<: *test_task_variables
    TASK: test:exchangers
test_helpers_2_6:
  <<: *test_task_2_6
  variables:
    <<: *test_task_variables
    TASK: test:helpers
test_jobs_2_6:
  <<: *test_task_2_6
  variables:
    <<: *test_task_variables
    TASK: test:jobs
test_lib_2_6:
  <<: *test_task_2_6
  variables:
    <<: *test_task_variables
    TASK: test:lib
test_models_2_6:
  <<: *test_task_2_6
  variables:
    <<: *test_task_variables
    TASK: test:models
test_services_2_6:
  <<: *test_task_2_6
  variables:
    <<: *test_task_variables
    TASK: test:services
test_validators_2_6:
  <<: *test_task_2_6
  variables:
    <<: *test_task_variables
    TASK: test:validators
