inherit_from:
  - http://relaxed.ruby.style/rubocop.yml

Style/ExpandPathArguments:
  Enabled: false

Lint/NonDeterministicRequireOrder:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false