AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'lib/generators/*/templates/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'plugins/**/*'
    - 'plugins-*/**/*'
    - 'lib/procedo/formula/language.rb'
    - 'lib/working_set/query_language.rb'
    - 'db/first_runs/**/*'
    - 'db/schema.rb'

Rails:
  Enabled: true

Rails/HttpPositionalArguments:
  Enabled: false

Rails/ApplicationRecord:
  Enabled: false

Rails/ApplicationJob:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/UnifiedInteger:
  Enabled: false

Metrics/MethodLength:
  Max: 60

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Metrics/AbcSize:
  Enabled: false
