---
version: '3'
services:
  db:
    container_name: ekylibre_development_db
    environment:
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=postgres'
      - 'TZ=Europe/Paris'
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    volumes:
      - ./data:/var/lib/postgresql/data
  app:
    container_name: ekylibre_development_app
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - 3000:3000
    build:
      context: .
    environment:
      - 'RAILS_ENV=development'
    command: [ "/opt/startup.sh" ]
    expose:
      - '3000'
    volumes:
      - ./public:/app/public
  redis:
    container_name: ekylibre_development_redis
    restart: always
    image: redis:5.0-alpine
    volumes:
      - redis:/var/lib/redis/data
  sidekiq:
    container_name: ekylibre_development_sidekiq
    restart: always
    depends_on:
      - redis
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/app
    environment:
      - 'RAILS_ENV=development'
      - 'REDIS_URL=redis://redis'

volumes:
    redis:
