json.specie resource.specie
json.started_on resource.started_on
json.stopped_on resource.stopped_on
json.start_state_of_production resource.start_state_of_production
json.life_duration resource.life_duration