# THESE FOLLOWING ACTIONS ARE PUBLICLY ACCESSIBLE
#     - "backend/master_vine_varieties#unroll_rootstocks"
#     - "backend/master_vine_varieties#unroll_vine_varieties"
#     - "backend/registered_postal_zones#unroll"
#     - "backend/registered_protected_designation_of_origins#unroll"

cvi_cadastral_plants:
  read:
    actions:
    - "backend/cvi_cadastral_plants#delete_modal"
    - "backend/cvi_cadastral_plants#edit"
    - "backend/cvi_cadastral_plants#index"
  write:
    dependencies:
    - read-cvi_cadastral_plants
    actions:
    - "backend/cvi_cadastral_plants#destroy"
    - "backend/cvi_cadastral_plants#update"

cvi_cultivable_zones:
  read:
    actions:
    - "backend/cvi_cultivable_zones#delete_modal"
    - "backend/cvi_cultivable_zones#edit"
    - "backend/cvi_cultivable_zones#edit_cvi_land_parcels"
    - "backend/cvi_cultivable_zones#index"
    - "backend/cvi_cultivable_zones#list_cvi_land_parcels"
    - "backend/cvi_cultivable_zones#show"
  write:
    dependencies:
    - read-cvi_cultivable_zones
    actions:
    - "backend/cvi_cultivable_zones#confirm_cvi_land_parcels"
    - "backend/cvi_cultivable_zones#destroy"
    - "backend/cvi_cultivable_zones#generate_cvi_land_parcels"
    - "backend/cvi_cultivable_zones#update"

cvi_land_parcels:
  read:
    actions:
    - "backend/cvi_land_parcels#edit"
    - "backend/cvi_land_parcels#index"
    - "backend/cvi_land_parcels#pre_split"
  write:
    dependencies:
    - read-cvi_land_parcels
    actions:
    - "backend/cvi_land_parcels#group"
    - "backend/cvi_land_parcels#split"
    - "backend/cvi_land_parcels#update"

cvi_statements:
  read:
    actions:
    - "backend/cvi_statements#edit"
    - "backend/cvi_statements#index"
    - "backend/cvi_statements#list"
    - "backend/cvi_statements#list_cvi_cadastral_plants"
    - "backend/cvi_statements#list_cvi_cadastral_plants_map"
    - "backend/cvi_statements#new"
    - "backend/cvi_statements#show"
  write:
    dependencies:
    - read-cvi_statements
    actions:
    - "backend/cvi_statements#create"
    - "backend/cvi_statements#destroy"
    - "backend/cvi_statements#update"

cvi_statement_conversions:
  read:
    actions:
    - "backend/cvi_statement_conversions#show"
    - "backend/cvi_statement_conversions#list_cvi_cultivable_zones"
  write:
    dependencies:
    - read-cvi_statement_conversions
    actions:
    - "backend/cvi_statement_conversions#create"
    - "backend/cvi_statement_conversions#reset"
    - "backend/cvi_statement_conversions#convert"

cadastral_land_parcel_zones:
  read:
    actions:
    - "backend/cadastral_land_parcel_zones#index"